Add events and ec track
orcestra-campaign/flight_segmentation pull request #69
Opened 2024-10-22 12:18 UTC by tmieslinger

This PR adds next to the segments also a list of `events` and loads and plots the EC track in the template.

2024-10-22 13:08 UTC, tmieslinger commented
I added the attribute `distance` that can be added to an `event`. I would assume that we usually want to note down the distance to the target for overpasses and underpasses and it's nice to have it as an attribute to be able to extract the info easily.

2024-10-23 13:24 UTC, tmieslinger commented
@Lucalino The last chunk of changes mostly add two features:
* circle center coordinates and radius are added automatically as soon as a kinds=`circle` is defined
* the EC meeting point is added to the `events` list. This closes issue #54 and  #68.
* some clean up

I hope we are at a state now that we have most relevant infos at hand and can start segmenting all flights ;-)

2024-10-23 15:08 UTC, Lucalino requested changes
Overall, this request adds super useful new features and most things work as expected. The only major trouble I had was with the `overpass_point` function which seems to require more input than defined (`seg`). But perhaps I overlooked/didn't understand something in which case an update of the accompanying information would be great. 

Apart from this issue, I recommend adding a few more cells were typical overpass calculations are performed so that not everyone needs to piece these code snippets together by themselves.

2024-10-23 15:13 UTC, tmieslinger commented on scripts/segmentation_template.md
> +- `cvao_overpass`
yes, the [CVAO](https://orcestra-campaign.org/cvao.html) is the ground station near Mindelo. As we also attribute the BCO by it's actual name I thought that it's consistent to name the other station accordingly.

2024-10-23 15:36 UTC, tmieslinger commented on scripts/utils.py
> +def get_overpass_point(ds, target_lat, target_lon):
that was a bug :) thanks for pointing out. It's corrected now.

2024-10-23 15:37 UTC, tmieslinger commented on scripts/segmentation_template.md
> +    ec_event(ds, ec_track),
* I added another example event in from of a dictionary in the template file
* BCO and CVAO can easily be loaded via `from orcestra import bco, mindelo`. We could add that by default to the cell that loads all modules. So far, I left it out as not all flights will need it.
* METEOR and PACE tracks: would be nice to add. Maybe the first person segmenting a flight that includes such segments can work on that?

2024-10-23 16:59 UTC, tmieslinger commented on scripts/segmentation_template.md
> +from utils import *
see comments above. This is covered by the commits adding PACE and METEOR tracks.

2024-10-23 19:02 UTC, tmieslinger commented on scripts/segmentation_template.md
> +plt.plot(ec_track.lon, ec_track.lat, c='C1', ls='dotted')
You found the one and only research flight that explicitly and by design did not try to meet EC, nor any other satellite and spontaneously also not the METEOR ship :D
[-> see flight report](https://orcestra-campaign.org/reports/HALO-20240821a.html) without any sign of EC

2024-10-23 19:22 UTC, tmieslinger commented on scripts/segmentation_template.md
> +plt.plot(ec_track.lon, ec_track.lat, c='C1', ls='dotted')
However, I did add a "refinement" to the `get_ec_track` function to select the EC track data for the time between aircraft takeoff and landing. Seems cleaner than the hack before.

2024-10-24 08:31 UTC, Lucalino commented on scripts/segmentation_template.md
> +plt.plot(ec_track.lon, ec_track.lat, c='C1', ls='dotted')
Haha, sorry for not checking the flight report more carefully. What a coincidence. 😅

2024-10-24 08:35 UTC, tmieslinger commented on scripts/segmentation_template.md
> +    ec_event(ds, ec_track),
hm... so the way the PACE track was derived during the campaign (and also the way it's currently implemented) does not work well after the actual overpass event as it's becoming more uncertain and drifts away from the actual track with time passing. This needs to be changed to load the true PACE track infos for dates in teh past!

2024-10-24 08:57 UTC, Lucalino commented
Thank you for the updates! I think, everything is quite clear now and I'll merge the branch. Happy segmenting everyone! 🙌

2024-10-24 08:57 UTC, merged

2024-10-24 09:02 UTC, tmieslinger commented
As mentioned above, the PACE track is incorrect (drifts with time). I am on it and will create a separate PR with a correction.